# falco_rules_local.yaml
# Custom detection rules for the linux-setup project

# Core macros required for rules

- macro: spawned_process
  condition: (evt.type = execve and evt.dir = <)

- macro: system_procs
  condition: (user.name = root or proc.name in (systemd, cron, crond, atd, dbus-daemon, rsyslogd, systemd-networkd))

- macro: shell_procs
  condition: (proc.name in (bash, sh, dash, zsh, ash, csh, ksh, fish))

- macro: shell_users
  condition: (user.name in (root, vagrant, ubuntu, ec2-user, centos, containerd-shim))

# Safe outbound destinations/ports:
# - ALWAYS quote string literals (host:port)
# - Keep IP literals quoted when used as strings (fd.sip compares to strings)
- macro: known_safe_outbound_connections
  condition: >
    (fd.sport in (53, 123)) or
    ((fd.sport in (80, 443)) and (fd.sip in ("127.0.0.1", "::1"))) or
    (fd.name in (
      "ntp.ubuntu.com:123",
      "security.ubuntu.com:80",
      "archive.ubuntu.com:80",
      "deb.debian.org:80",
      "mirrors.edge.kernel.org:80",
      "packages.microsoft.com:443"
    ))

# ---- Rules ----

- rule: Unexpected Outbound Connection from System Service
  desc: A system service established an outbound connection that is not on the safe list.
  condition: >
    evt.type = connect and
    fd.type in (ipv4, ipv6) and
    (system_procs or proc.pname pmatch (/usr/sbin/*, /usr/lib/*)) and
    not (known_safe_outbound_connections)
  output: "Unexpected outbound connection from system service (cmd=%proc.cmdline conn=%fd.name user=%user.name parent=%proc.pname)"
  priority: WARNING
  tags: [network, mitre_lateral_movement]

- rule: Shell Spawned by Non-Interactive Service
  desc: A shell was spawned by a non-interactive system service or daemon.
  condition: |
    spawned_process and
    shell_procs and
    not (proc.pname in (runc, docker, containerd, systemd)) and
    not (shell_users) and
    not (
      proc.pcmdline startswith "kubectl exec" or
      proc.pcmdline startswith "docker exec" or
      proc.pcmdline startswith "systemd-run --scope" or
      proc.pcmdline startswith "su -" or
      proc.pcmdline startswith "sudo -i" or
      proc.pcmdline startswith "login" or
      proc.pcmdline startswith "sshd:"
    )
  output: "Shell spawned by non-interactive service (cmd=%proc.cmdline parent=%proc.pname pcmd=%proc.pcmdline user=%user.name)"
  priority: WARNING
  tags: [process, mitre_execution]

- rule: Write to Sensitive File Under /etc
  desc: A process attempted to write to a sensitive file in /etc (passwd, shadow, sudoers, sshd_config, ...).
  condition: >
    evt.type in (open, openat, creat) and
    evt.is_open_write = true and
    fd.typechar = f and
    fd.name pmatch (/etc/passwd, /etc/shadow, /etc/group, /etc/gshadow, /etc/sudoers, /etc/ssh/sshd_config, /etc/crontab, /etc/fstab)
  output: "Write attempt to sensitive file under /etc (cmd=%proc.cmdline file=%fd.name user=%user.name parent=%proc.pname)"
  priority: WARNING
  tags: [filesystem, mitre_persistence, mitre_privilege_escalation]

- rule: Unexpected Outbound by Root Service
  desc: A root-owned system service initiated an unexpected outbound connection.
  condition: >
    evt.type = connect and
    user.uid = 0 and
    (proc.name in (systemd, sshd, cron, crond, dbus-daemon, rsyslogd, systemd-networkd) or
     proc.pname in (systemd, cron, crond, dbus-daemon, rsyslogd)) and
    fd.sip != "127.0.0.1" and fd.sip != "::1" and
    not (fd.sport in (53, 123)) and
    not (known_safe_outbound_connections)
  output: "ALERT: root service outbound (pid=%proc.pid proc=%proc.name cmd=%proc.cmdline dst=%fd.sip:%fd.sport parent=%proc.pname)"
  priority: WARNING
  tags: [linux-setup, mitre_lateral_movement, network]

- rule: Write Executable in Temp Directory
  desc: An executable-looking file was created in a temporary directory (common malware staging).
  condition: >
    evt.type in (open, openat, creat) and
    evt.is_open_write = true and
    fd.directory in (/tmp, /var/tmp, /dev/shm) and
    (fd.name endswith ".sh" or
     fd.name endswith ".so" or
     fd.name endswith ".bin" or
     fd.name endswith ".out" or
     fd.name endswith ".run" or
     fd.name endswith ".elf")
  output: "Executable-looking file written to temp dir (user=%user.name file=%fd.name parent=%proc.pname cmd=%proc.cmdline)"
  priority: NOTICE
  tags: [linux-setup, mitre_defense_evasion, malware]
